sudo: required
services:
  #  tell travis to install a copy of docker
  - docker

before_install:
  - docker build -t cronnevik/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run cronnevik/docker-react-tutorial npm run test -- --coverage
