sudo: required
services:
  #  tell travis to install a copy of docker
  - docker

before_install:
  - docker build -t cronnevik/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run cronnevik/docker-react-tutorial npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-tutorial"
  env: "DockerReactTutorial-env"
  bucket_name: "elasticbeanstalk-us-east-2-468343884841"
  bucket_path: "docker-react-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"